Support for requirement attribute testing
venkatesh-sivaraman/fireroad-server pull request #4
Opened 2019-01-29 06:55 UTC by georgiashay

Adds support for HASS/CI/GIR requirement testing
Adds support for generic courses 

Has been merged with the auth fix branch already

2019-01-31 05:13 UTC, venkatesh-sivaraman requested changes
Logic is good but needs a bit of reorganization - see comments. Thanks :)

2019-01-31 05:13 UTC, venkatesh-sivaraman commented on catalog/models.py
>          # TODO: GIR/HASS/CI
Remove todo

2019-01-31 05:13 UTC, venkatesh-sivaraman commented on requirements/views.py
> +            if("." not in subject_id):
Remove parens

2019-01-31 05:13 UTC, venkatesh-sivaraman commented on requirements/views.py
> +                attribute_dict = dict()
I think you can make this a bit less hacky. It would be better if instead of `CourseAttributeLists`, you had separate classes for `GIRAttribute`, `HASSAttribute`, and `CommunicationAttribute`. Then you could have each class have a class method that tries to parse a requirement string, and returns an instance if it corresponds to that requirement or `None` otherwise. Instead of the `tested_attributes` variable you can have a list of classes `[GIRAttribute, HASSAttribute, CommunicationAttribute]` declared in `catalog/models.py`.

2019-01-31 23:00 UTC, georgiashay commented on requirements/views.py
> +                attribute_dict = dict()
I've added the attribute classes to get rid of the hacky `__dict__` thing.  I'm not sure if it's exactly what you were looking for, but if it's not I can definitely rework it again.

2019-02-01 18:41 UTC, venkatesh-sivaraman reviewed
Ok, looks a lot better, I just added some minor comments to help streamline what you've written before we merge.

2019-02-01 18:41 UTC, venkatesh-sivaraman commented on catalog/models.py
> +    """Class that describes an attribute.
This is a lot better. Stylistically, a few minor things:
1. Move method documentation into the method itself.
2. Name all variables and methods consistently with the rest of the codebase: `foo_bar`, not `foobar` or `fooBar`.

2019-02-01 18:41 UTC, venkatesh-sivaraman commented on requirements/views.py
> +                #potential a generic course
Can you move this into a `Course` static method, e.g. `Course.make_generic(subject_id, unique_id)`? This method could raise a `ValueError` if it's not a generic course, prompting the "does not exist in catalog" warning. I think that would clean up the `progress` method quite a bit.

2019-02-01 23:12 UTC, venkatesh-sivaraman approved these changes

2019-02-01 23:12 UTC, merged